# Generated by Django 2.0.13 on 2020-05-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=255)),
                ('employee_city', models.ForeignKey(on_delete='cascade', related_name='employee_city', to='company.City')),
                ('employee_title', models.ForeignKey(on_delete='cascade', related_name='employee_title', to='company.Title')),
            ],
        ),
    ]
